name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - CPCluster_masterNode
          - CPCluster_node
          - cpcluster_common
          - cpcluster_client

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Build ${{ matrix.project }}
      working-directory: ${{ matrix.project }}
      run: cargo build --verbose

    - name: Run tests for ${{ matrix.project }}
      working-directory: ${{ matrix.project }}
      run: cargo test --verbose
